package com.lh.rapid.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TEST".
 */
@Entity
public class Test {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String test;

    @Generated
    public Test() {
    }

    public Test(Long id) {
        this.id = id;
    }

    @Generated
    public Test(Long id, String test) {
        this.id = id;
        this.test = test;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTest() {
        return test;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTest(@NotNull String test) {
        this.test = test;
    }

}
